{"data": "Traceback (most recent call last):\n  File \"/Users/mhrezaei/Documents/Research/negation/negation-and-nlu/env/lib/python3.11/site-packages/jiant/utils/zlog.py\", line 39, in log_context\n    yield self\n  File \"/Users/mhrezaei/Documents/Research/negation/negation-and-nlu/env/lib/python3.11/site-packages/jiant/proj/main/runscript.py\", line 140, in run_loop\n    runner = setup_runner(\n             ^^^^^^^^^^^^^\n  File \"/Users/mhrezaei/Documents/Research/negation/negation-and-nlu/env/lib/python3.11/site-packages/jiant/proj/main/runscript.py\", line 92, in setup_runner\n    jiant_model_setup.delegate_load_from_path(\n  File \"/Users/mhrezaei/Documents/Research/negation/negation-and-nlu/env/lib/python3.11/site-packages/jiant/proj/main/modeling/model_setup.py\", line 90, in delegate_load_from_path\n    weights_dict = torch.load(weights_path)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/mhrezaei/Documents/Research/negation/negation-and-nlu/env/lib/python3.11/site-packages/torch/serialization.py\", line 986, in load\n    with _open_file_like(f, 'rb') as opened_file:\n         ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/mhrezaei/Documents/Research/negation/negation-and-nlu/env/lib/python3.11/site-packages/torch/serialization.py\", line 435, in _open_file_like\n    return _open_file(name_or_buffer, mode)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/mhrezaei/Documents/Research/negation/negation-and-nlu/env/lib/python3.11/site-packages/torch/serialization.py\", line 416, in __init__\n    super().__init__(open(name, mode))\n                     ^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: './models/roberta-large/model/roberta-large.p'\n", "TIMESTAMP": 1717325969.085995}
